### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by adobley** [adobley/yatda#5]
We need to setup an architecture with Java (1.8 preferred) and Spring to serve up the Angular app.

This will require some more complex configuration to have both our frontend development tooling and java development tooling. I'd prefer if we use Gradle rather than just Maven.

**Comment by adobley** [comment]
I'm working on this right now. I'm happy to hear suggestions. I'll *try* to have some incremental commits without breaking everything. But I'm playing around with my options.

**Comment by TWRaz** [comment]
I'm not sure this ought to be a priority. The most important thing to do is familiarize ourselves with some of the frontend tools we'll encounter since that's where the majority of new stories on the project will fall. 

Since the infrastructure is already established on the project we're going into, we should minimize time spent on setting shit up and focus on playing around with everything that's already there. While it's useful to know how to setup stuff, it's not a skill we'll need to utilize anytime soon. For now, I'd recommend having a service interface that just saves and retrieves todos from local browser storage, and work on replacing it with a backend once we nail the frontend.

**Comment by adobley** [comment]
That's a good point. I was thinking of just mocking out the server for now.
It's there and works, but it adds more weight to development.

**Comment by adobley** [comment]
To reduce noise in the repo, I'm going to drop the java code out for now. If we want it its both in the repo history and really not that complicated.
